### ISSUE TITLE
Placing transformer MFSU on the server will cause a crash

### ISSUE THREAD

**Issue by mcmso** [MC-U-Team/HyCraftHDs-WTF-Ic2-Addon#2] opened 2019-05-25 15:43 UTC
![image](https://user-images.githubusercontent.com/46519955/58371760-bdc8c300-7f46-11e9-83ff-17515e7ab741.png)
[crash-2019-05-25_23.41.25-server.txt](https://github.com/MC-U-Team/HyCraftHDs-WTF-Ic2-Addon/files/3219488/crash-2019-05-25_23.41.25-server.txt)

**Comment by MrTroble** [comment] 2019-05-25 17:02
Hello @mcmso,

can you please send us your server/client crash log and or console log.

Thanks and cheers,
~MrTroble

**Comment by HyCraftHD** [comment] 2019-05-25 17:11
Hello, thank you for the report. He already posted the crashlog @MrTroble.
This might be a duplicate of #1 
I'm currently investigating.
~Johannes

**Comment by MrTroble** [comment] 2019-05-25 17:12
Ohhh sorry was misreading that.

**Closed as completed** 2019-05-25 17:16 UTC
Labels: bug, duplicate

**Comment by HyCraftHD** [comment] 2019-05-25 17:20
Thank you very much for reporting @mcmso!
Here is the fixed version: https://minecraft.curseforge.com/projects/hycrafthds-wtf-ic2-addon/files/2715660

**Comment by mcmso** [comment] 2019-05-25 23:39
> Thank you very much for reporting @mcmso!
> Here is the fixed version: https://minecraft.curseforge.com/projects/hycrafthds-wtf-ic2-addon/files/2715660
Thank you very much for the fix and look forward to adding more new features
